# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170115_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friendusername',
            new_name='username',
        ),
        migrations.AddField(
            model_name='friend',
            name='wishes',
            field=models.ManyToManyField(to='polls.Wishes'),
        ),
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wishes',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='foo', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='bar', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='state_province',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wishes',
            name='occassion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wishes',
            name='wishitem',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
