# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170116_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Personuser',
        ),
    ]
