# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170116_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personuser',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='wishes',
            name='description',
        ),
        migrations.AddField(
            model_name='friend',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='personuser',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='wishes',
            name='descriptionwish',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
