# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170116_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='personuser',
            name='passwd',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
