# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_personuser_passwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='personuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='personuser',
            name='state_province',
        ),
        migrations.AddField(
            model_name='personuser',
            name='city_county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personuser',
            name='country_residence',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personuser',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
