# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170117_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='username',
        ),
        migrations.RemoveField(
            model_name='wishes',
            name='occasion_date',
        ),
        migrations.AddField(
            model_name='wishes',
            name='occassion_date',
            field=models.DateField(null=True),
        ),
    ]
