# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_delete_personuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
