# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_wishes_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='showwish',
            field=models.BooleanField(default=True),
        ),
    ]
