# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_wishes_showwish'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='hashid',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
