# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_wishes_hashid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
