# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_wishes_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
