# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 06:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0020_pool_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='user',
        ),
        migrations.AddField(
            model_name='pool',
            name='gifters',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
