# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_pool_opt02vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='opt01vote',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='opt02vote',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='opt03vote',
        ),
    ]
