# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_remove_pool_poolsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='extradetails',
            name='gender',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='extradetails',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
